#!/bin/bash

#setup debug config
export SBT_OPTS="-XX:MaxPermSize=256M -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9999"

function run {
    sbt -Dconfig.file=conf/dev.conf -Duser.timezone=UTC run
}

function build {
    compile
}

function compile {
    sbt compile
}

function teardown {
    cd test_data
    ./runMongoCmdLocal.sh localhost db_drop.js
    cd ..
}

function tear {
    teardown
}

function setup {
    tear
    cd test_data
    ./setupAll.sh runMongoCmdLocal.sh localhost
    cd ..
}

#handle input
if [ -n "$1" ]
then
	$1 $2 $3 $4 $5 $6 $7 $8
else
	run
fi
